# Generated by Django 5.2.1 on 2025-06-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocredencial',
            name='status_pedido',
            field=models.CharField(blank=True, choices=[('E', 'Em análise'), ('A', 'Aprovado'), ('R', 'Recusado')], default='A', max_length=1, null=True),
        ),
    ]
