# Generated by Django 5.2.1 on 2025-06-03 04:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pedidocredencial_status_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='conteudo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='extensao_arquivo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='nome_arquivo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tamanho_arquivo',
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(default=1, upload_to=app.models.upload_to_documento),
            preserve_default=False,
        ),
    ]
