# Generated by Django 5.2.1 on 2025-06-06 21:22

import cadastro.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCredencial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField()),
                ('status_pedido', models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_ibge', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='municipios', to='cadastro.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('pedido_credencial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='observacoes', to='cadastro.pedidocredencial')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucaoPedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('status_evolucao', models.CharField(blank=True, max_length=45, null=True)),
                ('pedido_credencial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='evolucoes', to='cadastro.pedidocredencial')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_documento', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=45)),
                ('arquivo', models.FileField(upload_to=cadastro.models.upload_to_documento)),
                ('pedido_credencial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentos', to='cadastro.pedidocredencial')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.PositiveSmallIntegerField()),
                ('estado_civil', models.PositiveSmallIntegerField()),
                ('cpf', models.CharField(max_length=45, unique=True)),
                ('rg', models.CharField(blank=True, max_length=45, null=True)),
                ('org_emissor_rg', models.CharField(blank=True, max_length=45, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True)),
                ('naturalidade', models.CharField(max_length=255)),
                ('nacionalidade', models.CharField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=45)),
                ('fone_residencial', models.CharField(blank=True, max_length=45, null=True)),
                ('fone_celular', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas_fisicas', to='cadastro.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas_fisicas', to='cadastro.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=45, unique=True)),
                ('insc_estadual', models.CharField(blank=True, max_length=45, null=True)),
                ('cod_cnae', models.CharField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=45)),
                ('fone', models.CharField(blank=True, max_length=45, null=True)),
                ('nome_responsavel', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas_juridicas', to='cadastro.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoas_juridicas', to='cadastro.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=255)),
                ('data_admissao', models.DateField()),
                ('renda', models.DecimalField(decimal_places=2, max_digits=15)),
                ('num_ctps', models.CharField(max_length=45)),
                ('pis_pasep', models.CharField(blank=True, max_length=45, null=True)),
                ('fone_comercial', models.CharField(max_length=45)),
                ('pessoafisica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vinculos', to='cadastro.pessoafisica')),
                ('pessoajuridica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vinculos', to='cadastro.pessoajuridica')),
            ],
        ),
        migrations.AddField(
            model_name='pedidocredencial',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_credencial', to='cadastro.vinculo'),
        ),
    ]
