# Generated by Django 5.2.1 on 2025-06-04 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCredencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status_pedido', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cod_ibge', models.CharField(max_length=20, unique=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='cadastro.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido_credencial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observacoes', to='cadastro.pedidocredencial')),
            ],
        ),
        migrations.CreateModel(
            name='EvolucaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_evolucao', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='RECEBIDO', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pedido_credencial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evolucoes', to='cadastro.pedidocredencial')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=255)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('extensao_arquivo', models.CharField(max_length=10)),
                ('tamanho_arquivo', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(choices=[('PDF', 'PDF'), ('IMAGEM', 'Imagem'), ('OUTRO', 'Outro')], max_length=20)),
                ('conteudo', models.BinaryField()),
                ('pedido_credencial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='cadastro.pedidocredencial')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.PositiveSmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino'), (3, 'Outro')])),
                ('estado_civil', models.PositiveSmallIntegerField(choices=[(1, 'Solteiro(a)'), (2, 'Casado(a)'), (3, 'Divorciado(a)'), (4, 'Viúvo(a)'), (5, 'Separado(a)')])),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('org_emissor_rg', models.CharField(blank=True, max_length=20, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=255, null=True)),
                ('naturalidade', models.CharField(max_length=255)),
                ('nacionalidade', models.CharField(max_length=255)),
                ('fone_residencial', models.CharField(blank=True, max_length=20, null=True)),
                ('fone_celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=10)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('insc_estadual', models.CharField(blank=True, max_length=45, null=True)),
                ('cod_cnae', models.CharField(blank=True, max_length=20, null=True)),
                ('fone', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_responsavel', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.municipio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('data_admissao', models.DateField()),
                ('renda', models.DecimalField(decimal_places=2, max_digits=15)),
                ('num_ctps', models.CharField(max_length=20)),
                ('pis_pasep', models.CharField(blank=True, max_length=20, null=True)),
                ('fone_comercial', models.CharField(max_length=20)),
                ('pessoafisica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='cadastro.pessoafisica')),
                ('pessoajuridica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='cadastro.pessoajuridica')),
            ],
        ),
        migrations.AddField(
            model_name='pedidocredencial',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_credencial', to='cadastro.vinculo'),
        ),
    ]
