# Generated by Django 5.2.1 on 2025-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
