# Generated by Django 5.2.1 on 2025-06-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_pessoafisica_naturalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocredencial',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
