# Generated by Django 5.2.1 on 2025-06-17 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_pedidocredencial_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocredencial',
            name='vinculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_credencial', to='cadastro.vinculo'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='pessoafisica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='cadastro.pessoafisica'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='pessoajuridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='cadastro.pessoajuridica'),
        ),
    ]
