# Generated by Django 5.2.1 on 2025-06-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logdeacesso_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdeacesso',
            name='resultado',
            field=models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro'), ('atencao', 'Atenção')], default='sucesso', max_length=7),
        ),
    ]
